version: "3.7"

services:
  mongo-rs0-1:
    image: "mongo-start"
    build: ./database/mongo-rs0-1
    ports:
      - "27020:27017"
    volumes:
      - ./database/mongo-rs0-1/data:/data/db
    depends_on:
      - "mongo-rs0-2"
      - "mongo-rs0-3"

  mongo-rs0-2:
    image: "mongo:3.6.0"
    command: --replSet rs0 --smallfiles --oplogSize 128
    ports:
      - "27021:27017"
    volumes:
      - ./database/mongo-rs0-2/data:/data/db

  mongo-rs0-3:
    image: "mongo:3.6.0"
    command: --replSet rs0 --smallfiles --oplogSize 128
    ports:
      - "27022:27017"
    volumes:
      - ./database/mongo-rs0-3/data:/data/db

  setup-rs-2:
    image: "setup-rs"
    build: ./database/setup
    depends_on:
      - "mongo-rs0-1"

  api-project:
    container_name: api-project
    build: .
    command: bash -c "yarn install; yarn dev"
    volumes:
      - .:/usr/src/api-project
    ports:
      - 3434:3434
    restart: always
    depends_on:
      - "setup-rs-2"


