const toysTitles = [
    "Fazendinha",
    "Mascotes Turma da Mônica",
    "Bonecos Giramille",
    "Boneca Mandinha na Banheira",
    "Boneca Cheirosinha",
    "Chute a Gol Apolo",
    "Car One PS Branco",
    "Sprint Turbo Militar 12v",
    "Baby Trike Azul",
    "Bolha de Sabão SlimySlime",
    "Bolha de sabão Frozen 2",
    "Praia Bubble, bolhas gigantes",
    "Bebê Surpresa",
    "Super Massa Cozinha Criativa",
    "Fábrica de Borrachas",
    "Carro Harry Potter",
    "Pista Elétrica Infantil Patrulha Canina",
    "Carro Mario Kart",
    "L.O.L Surprise!",
    "Nanana Surprise!",
    "Garagem S.A.",
    "Deck Pokémon Espada e Escudo",
    "Lata Pokébola 4",
    "Jogo Corrida Mágica",
    "Jogo Roda a Roda",
    "Jogo Topa ou Não Topa",
    "SOS Resgate",
    "Surf Studio da Barbie",
    "Adotados Clássico",
    "Hot Wheels – Wave Racers",
    "Bolinha de Gude",
    "Peteca", 
    "Bilboquê",
    "Ioiô",
    "Bambolê",
    "Forte Apache",
    "Pião",
    "Boneca Beijoca",
    "O Tijolinho Mágico",
    "Pega Varetas",
    "Boneco Topo Gigio",
    "Carrinho de Rolimã",
    "Bate-Bola",
    "Radio Flyer Wagon",
    "Chemistry Set",
    "Joy Buzzer",
    "Yo-Yo",
    "Pop-Up Book",
    "Stuffed Mickey Mouse",
    "Finger Paint",
    "Sock Monkey",
    "Buck Rogers Rocket Pistol",
    "Microscope Set",
    "Beach Ball",
    "Red Ryder BB Gun",
    "Army Men",
    "View-Master",
    "Bubble Solution",
    "Little Golden Books",
    "Slinky",
    "Magic 8 Ball",
    "Legos",
    "Water Balloon",
    "Silly Putty",
    "Fisher-Price Little People",
    "Colorforms",
    "Paint-by-Numbers Kit",
    "Mr. Potato Head",
    "Wiffle Ball",
    "Matchbox Car",
    "PEZ Dispenser",
    "Gumby",
    "Play-Doh",
    "Tonka Truck",
    "Frisbee",
    "Corn Popper",
    "Two-Handed Pogo Stick",
    "Hula Hoop",
    "Barbie",
    "Troll Doll",
    "Plarail Toy Train",
    "Chatty Cathy",
    "Fake Vomit",
    "Etch A Sketch",
    "Rock-a-Stack",
    "Ken",
    "Slip n Slide",
    "Chatter Telephone",
    "G.I. Joe",
    "Easy-Bake Oven",
    "Creepy Crawlers",
    "Rockem Sockem Robots",
    "Johnny Seven O.M.A.",
    "See n Say",
    "SuperBall",
    "Barrel of Monkeys",
    "Radio-Controlled Car",
    "Lite-Brite",
    "Hot Wheels",
    "Playmobil",
    "Flatsy Doll",
    "Barbies Dream House",
    "NERF Ball",
    "Weebles",
    "Paddington Bear",
    "Baby Alive",
    "Shrinky Dinks",
    "Magna Doodle",
    "Rubiks Cube",
    "Stretch Armstrong",
    "Star Wars Action Figure",
    "Mattel Classic Football",
    "Simon",
    "Speak and Spell",
    "Star Trek Electronic Phasers"
];

module.exports.toysTitles = toysTitles;
